import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/NavBar";
import Nav from "./components/Nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons:'./assets/portfolio.png'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en " className="dark">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen dark:bg-[#171717] bg-[#FFFAED]  text-black dark:text-white`}
      >
        <>
        <section className="  ">
          <div className="container pt-8 lg:flex-row flex flex-col ">
            <div className="lg:w-1/3 w-full  pl-5 pr-5 pb-5">
              <Nav />
            </div>
            <div className="lg:w-2/3  p-5 w-full  border border-gray-600 rounded-bl-3xl rounded-tr-3xl ">
              <NavBar />  
              {children}
            </div>
          </div>
          </section>
        </>
      </body>
    </html>
  );
}
